#  Data Preprocessing in Machine Learning

Author: Varun Singh

## Objective
Learn how to prepare raw data before training a Machine Learning model.

## What is Data Preprocessing?

Data Preprocessing is the process of cleaning and transforming raw data into a format that is suitable for Machine Learning algorithms.

### Steps:
- Import Libraries
- Load Dataset
- Explore Dataset
- Handle Missing Values
- Encode Categorical Data
- Feature Scaling
- Split Dataset

In [1]:
# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Libraries Imported Successfully ")

Libraries Imported Successfully

## Create a Sample Dataset

In [2]:
# Creating a sample dataset

data = {
    "Name": ["Aman", "Rahul", "Priya", "Neha", "Rohit"],
    "Age": [23, 25, np.nan, 22, 24],
    "Salary": [25000, 30000, 28000, np.nan, 32000],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)

df

    Name   Age   Salary    City
0   Aman  23.0  25000.0   Delhi
1  Rahul  25.0  30000.0  Mumbai
2  Priya   NaN  28000.0   Delhi
3   Neha  22.0      NaN    Pune
4  Rohit  24.0  32000.0  Mumbai

## Check Dataset Information

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     4 non-null      float64
 2   Salary  4 non-null      float64
 3   City    5 non-null      object
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

In [4]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   23.500000  28750.000000
std     1.290994   2986.078811
min    22.000000  25000.000000
25%    22.750000  27250.000000
50%    23.500000  29000.000000
75%    24.250000  30500.000000
max    25.000000  32000.000000

In [5]:
df.isnull().sum()

Name      0
Age       1
Salary    1
City      0
dtype: int64

## Handle Missing Values

In [6]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df

    Name   Age   Salary    City
0   Aman  23.0  25000.0   Delhi
1  Rahul  25.0  30000.0  Mumbai
2  Priya  23.5  28000.0   Delhi
3   Neha  22.0  28750.0    Pune
4  Rohit  24.0  32000.0  Mumbai

## Encode Categorical Data

In [7]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["City"] = encoder.fit_transform(df["City"])

df

    Name   Age   Salary  City
0   Aman  23.0  25000.0     0
1  Rahul  25.0  30000.0     1
2  Priya  23.5  28000.0     0
3   Neha  22.0  28750.0     2
4  Rohit  24.0  32000.0     1

## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["Age", "Salary"]] = scaler.fit_transform(df[["Age", "Salary"]])

df

    Name  Age    Salary  City
0   Aman -0.5 -1.621266     0
1  Rahul  1.5  0.540422     1
2  Priya  0.0 -0.324253     0
3   Neha -1.5  0.000000     2
4  Rohit  0.5  1.405098     1

## Separate Features and Target

In [9]:
X = df[["Age", "Salary", "City"]]

y = [1, 0, 1, 0, 1]

print(X)

print(y)

   Age    Salary  City
0 -0.5 -1.621266     0
1  1.5  0.540422     1
2  0.0 -0.324253     0
3 -1.5  0.000000     2
4  0.5  1.405098     1
[1, 0, 1, 0, 1]

## Train-Test Split

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data")

print(X_train)

print("Testing Data")

print(X_test)

Training Data
   Age    Salary  City
4  0.5  1.405098     1
2  0.0 -0.324253     0
0 -0.5 -1.621266     0
3 -1.5  0.000000     2
Testing Data
   Age    Salary  City
1  1.5  0.540422     1

# ✅ Key Learnings

- Imported Python libraries
- Created a sample dataset
- Explored the dataset
- Handled missing values
- Encoded categorical values
- Applied feature scaling
- Split data into training and testing sets

🎯 Data is now ready for Machine Learning.